global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'prometheus-rules.yml'

scrape_configs:
  - job_name: 'ftso-provider'
    static_configs:
      - targets: ['ftso-provider:3101']
    scrape_interval: 5s
    metrics_path: '/metrics/prometheus'
    honor_labels: true

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
